export const KeyboardShortcuts = [
  {
    id: 'c-play',
    type: 'command',
    title: '/play <tên bài>',
    description: 'Phát ngay một bài hát theo tên',
    shortcut: 'Tab',
    commandName: '/play',
  },
  {
    id: 'c-playall',
    type: 'command',
    title: '/playall',
    description: 'Phát toàn bộ danh sách bài hát',
    shortcut: 'Tab',
    commandName: '/playall',
  },
  {
    id: 'c-queue',
    type: 'command',
    title: '/queue <tên bài>',
    description: 'Thêm bài hát vào hàng chờ phát',
    shortcut: 'Tab',
    commandName: '/queue',
  },
  {
    id: 'c-pause',
    type: 'command',
    title: '/pause',
    description: 'Tạm dừng bài hát đang phát',
    shortcut: 'Tab',
    commandName: '/pause',
  },
  {
    id: 'c-next',
    type: 'command',
    title: '/next',
    description: 'Chuyển sang bài hát tiếp theo',
    shortcut: 'Tab',
    commandName: '/next',
  },
  {
    id: 'c-volume',
    type: 'command',
    title: '/volume <0-100>',
    description: 'Điều chỉnh mức âm lượng phát',
    shortcut: 'Tab',
    commandName: '/volume',
  },
  {
    id: 'c-theme',
    type: 'command',
    title: '/theme <dark|light>',
    description: 'Thay đổi giao diện sáng hoặc tối',
    shortcut: 'Tab',
    commandName: '/theme',
  },
  {
    id: 'c-help',
    type: 'command',
    title: '/help',
    description: 'Hiển thị danh sách tất cả câu lệnh',
    shortcut: 'Tab',
    commandName: '/help',
  },
]

export const CmdQuickActions = [
  {
    id: 'qa-1',
    type: 'action',
    title: 'Phát ngẫu nhiên thư viện',
    description: 'Chức năng • Trộn bài hát ngẫu nhiên',
    shortcut: '⌥P',
  },
  {
    id: 'qa-2',
    type: 'action',
    title: 'Đi tới Thư viện nhạc',
    description: 'Điều hướng • Mở trang My Music',
    shortcut: 'G M',
  },
  {
    id: 'qa-3',
    type: 'action',
    title: 'Đi tới Đang phát',
    description: 'Điều hướng • Mở trang Now Playing',
    shortcut: 'G P',
  },
]
